FROM ubuntu:20.04

RUN apt update
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN pip3 install numpy==1.19
RUN pip3 install docker==2.5.0

RUN echo "some text" > /some_file
